// Automatically generated by MockGen. DO NOT EDIT!
// Source: ../vendor/github.com/cloudfoundry/libbuildpack/yaml.go

package finalize_test

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of YAML interface
type MockYAML struct {
	ctrl     *gomock.Controller
	recorder *_MockYAMLRecorder
}

// Recorder for MockYAML (not exported)
type _MockYAMLRecorder struct {
	mock *MockYAML
}

func NewMockYAML(ctrl *gomock.Controller) *MockYAML {
	mock := &MockYAML{ctrl: ctrl}
	mock.recorder = &_MockYAMLRecorder{mock}
	return mock
}

func (_m *MockYAML) EXPECT() *_MockYAMLRecorder {
	return _m.recorder
}

func (_m *MockYAML) Load(file string, obj interface{}) error {
	ret := _m.ctrl.Call(_m, "Load", file, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockYAMLRecorder) Load(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Load", arg0, arg1)
}

func (_m *MockYAML) Write(dest string, obj interface{}) error {
	ret := _m.ctrl.Call(_m, "Write", dest, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockYAMLRecorder) Write(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Write", arg0, arg1)
}
