// Code generated by MockGen. DO NOT EDIT.
// Source: finalize.go

package finalize_test

import (
	gomock "github.com/golang/mock/gomock"
)

// MockYAML is a mock of YAML interface
type MockYAML struct {
	ctrl     *gomock.Controller
	recorder *MockYAMLMockRecorder
}

// MockYAMLMockRecorder is the mock recorder for MockYAML
type MockYAMLMockRecorder struct {
	mock *MockYAML
}

// NewMockYAML creates a new mock instance
func NewMockYAML(ctrl *gomock.Controller) *MockYAML {
	mock := &MockYAML{ctrl: ctrl}
	mock.recorder = &MockYAMLMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockYAML) EXPECT() *MockYAMLMockRecorder {
	return _m.recorder
}

// Load mocks base method
func (_m *MockYAML) Load(_param0 string, _param1 interface{}) error {
	ret := _m.ctrl.Call(_m, "Load", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load
func (_mr *MockYAMLMockRecorder) Load(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Load", arg0, arg1)
}
