// Automatically generated by MockGen. DO NOT EDIT!
// Source: finalize.go

package finalize_test

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of YAML interface
type MockYAML struct {
	ctrl     *gomock.Controller
	recorder *_MockYAMLRecorder
}

// Recorder for MockYAML (not exported)
type _MockYAMLRecorder struct {
	mock *MockYAML
}

func NewMockYAML(ctrl *gomock.Controller) *MockYAML {
	mock := &MockYAML{ctrl: ctrl}
	mock.recorder = &_MockYAMLRecorder{mock}
	return mock
}

func (_m *MockYAML) EXPECT() *_MockYAMLRecorder {
	return _m.recorder
}

func (_m *MockYAML) Load(_param0 string, _param1 interface{}) error {
	ret := _m.ctrl.Call(_m, "Load", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockYAMLRecorder) Load(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Load", arg0, arg1)
}
